import { chromium } from "playwright";
const out = process.argv[2];
const b = await chromium.launch({ args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errs = []; p.on("pageerror", (e) => errs.push(e.message));
await p.goto("http://localhost:3100/", { waitUntil: "load" });
await p.waitForTimeout(7000);
await p.evaluate(() => { const s = window.__console.getState(); s.setDate("2023-06-22"); s.setSelected(0); });
await p.waitForTimeout(4000);
await p.screenshot({ path: `${out}/desktop_block.png` });
console.log(errs.join("\n") || "no errors");
await b.close();
